### ISSUE TITLE
Stop queue receive after sigterm

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-queue#101]
Po nahození do ECS dostane receive command SIGTERM v moment kdy ECS bude požadovat vypnutí kontejneru. 
Pokud zrovna bude zpracováván job tak ten doběhne pokud nedojde k timeoutu `ECS_CONTAINER_STOP_TIMEOUT ` (ten nastavíme na 24h).
V moment kdy job doběhne a fronta se chystá vybrat nový tak zkontrolujeme jestli process nedostal `SIGTERM` a pokud ano ukončí se. Tím se zajistí že už se nebudou vybírat nové joby.
Je potřeba ověřit že to bude dobře fungovat se supervisorem který to ještě bude obalovat.

Implementace v connection:
```php
        pcntl_signal(SIGTERM, function ($signo) {
            print "Queue receive stopped by signal $signo";
            exit(0);
        });
        do {
            $this->_getDb()->closeConnection();
            pcntl_signal_dispatch();
            $this->_receive($worker);
            gc_collect_cycles();
        } while ((time() - $startTime) < $maxRunTime);
```

https://github.com/keboola/connection/blob/a54867e49797359df7fa4e9c2ba0e4882de19f96/application/modules/storage/cli-commands/QueueReceive.php#L68

**Comment by ujovlado** [comment]
tak som sa s tym pobavil, vyzera, ze to bude valit ... pred "processing message finished" som dal sleep. pockalo to.

![Screenshot_2019-05-07_12-40-26](https://user-images.githubusercontent.com/419849/57296241-cc048b80-70cc-11e9-9e70-533b6250efb8.png)

**Comment by Halama** [comment]
super, s tím jsi teda poeditovat to queue receive aby se to ukončilo a nepokračovalo v pollování?

**Comment by ujovlado** [comment]
Jj, ten isty kod co v connection. Akurat sa to chvilku spravalo divne, mal som tam phpckovy sleep, s ktorym to blblo. :) A este zmena supervisor configu.
