### ISSUE TITLE
Kill queues garbage collection

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-queue#102]
V dockerized verzi poběží killl receive commandy v kontejneru který bude mít vlastní network interface s vlastním hostname např. `ip-10-0-41-40.ec2.internal`.
A k tomu vytvořený:
- Alarm - `Syrup syrup_kill_ip_10_0_41_40_ec2_internal queue is full`
- SQS - `syrup_kill_ip-10-0-40-102-ec2-internal`
TODO: proč to není stejné? @ujovlado v alarmu jsou podtržítka v SQS pomlčky. 

Nebude na to tedy fungovat současný [Garbage Collector ](https://github.com/keboola/queue-garbage-collector) který kontroluje jméno instance a jméno fronty.

Napadá mě řešení ve kterém by se v reakci na sigterm v kill receive (podobně jako https://github.com/keboola/syrup-queue/issues/101) commandu fronta a alarm smázly předtím než se to ukončí. Nereagovalo by to ale na tvrdé vypnutí instance, to by se ale teoreticky vůbec dít nemělo, u spotů reagujeme na notifikaci o plánovaném vypnutí a instanci v ECS drainujeme.

**Comment by ujovlado** [comment]
> TODO: proč to není stejné? @ujovlado v alarmu jsou podtržítka v SQS pomlčky.

asi si si vybral dva rozne ... ja som to potom zjednocoval na podtrzitka.

Premazem ich, spravim deploy a checknem, ci je to rovnake.

**Comment by Halama** [comment]
aha, to je možný. ok dík

**Comment by ujovlado** [comment]
Po deployi.

sqs:

![Screenshot_2019-05-07_17-29-35](https://user-images.githubusercontent.com/419849/57312406-c3707d00-70ed-11e9-8edb-4d940b6817d9.png)

alarmy:

![Screenshot_2019-05-07_17-29-46](https://user-images.githubusercontent.com/419849/57312427-d1be9900-70ed-11e9-80a5-fb0103c2ab2f.png)

**Comment by ujovlado** [comment]
Tuna moze nastat dost divna race condition. V containeri nam pobezi aj receive a aj receive-kill.

Ked pride deploy a bude tam bezat nejaky job, tak zavolanie "docker stop" na ten container bude poslane do supervisora a ten sa bude nasledne snazit povypinat svoje programy.

- standardny receive pocka na dokoncenie jobu, tam je to caj
- receive-kill vsak neriesi ci tam nejaky job bezi alebo nie a tak po prijati sigterm moze skoncit rovno

Moze sa teda stat, ze ten dlhsie beziaci job by uz potom nebolo mozne zabit. Pretoze uz tam nebude bezat receive-kill a kill fronta alarm by boli zmazane.

Je to teda specificky pripad, kedy by chcel niekto zabit job pocas deployamentu.

Moc sa mi to teda nepaci ... idealne by bolo aby sa ten receive-kill stopoval posledny.

@Halama alebo je to prijatelne?

**Comment by Halama** [comment]
To je super postřeh, tahle situace mi vůbec nedošla. Přijatelné to určitě není, to by se nám okamžitě vrátilo:) Co s tím? je nějak řešitelné to pořadí stopování?

**Comment by ujovlado** [comment]
Supervisor ma nejake `priority` pri programoch, tak vyskusam najprv to.

**Comment by ujovlado** [comment]
Tu som zabudol dopisat. To `priority` nepomoze, riesi to vlastne len postupnost nahadzovania a killovania (skusal som to, necakaju na seba a je to vlastne celkom logicke).

Recevice kill asi skusime upravit tak, ze ked dostane signal SIGTERM, tak si zacne checkovat, ci bezi `queue-receive` (normalne cez `ps aux` + `grep` alebo tak). Akonahle zisti, ze nebezi, tak by zmazal alarm a pod a potom sa ukoncil. Snad to pofici.

**Comment by ujovlado** [comment]
S tymto som sa este bavil v piatok.

Celkom dobre sa mi myslim podarilo vyriesit situaciu, kedy prisiel sigterm a mame tam beziaci job. Receive-kill pocka na ukoncenie posledneho programu supervisora az tak sa sam ukonci, beziace joby pozera cez `pgrep -P 1` -> t.j. vsetky child processy supervisora (supervisor bezi, ako prvy command v containeri, s PID 1). Akonahle tam bezi uz len 1 viem, ze je to receive-kill a mozem ho ukoncit. Na to poslem maly PR.

Co sa tyka garbage collection, asi by som to radsej vyriesil mimo tohto, kludne tiez nejakou lambdou, ktora by skontrolovala tie queue names -> vytvorila si z toho IPcky a kukla ci su tam tie ENI.

Chcem to tak preto, lebo tam existuje kill queue aj pre ten apache a tu nemame myslim ako zmazat pri vypnuti apache. Cize garbage collection sa asi nevyhneme.

**Comment by Halama** [comment]
aha, jasně to s tím apachem je pravda. Tím pádem by měl supervisor s killl queue startovat i v tom apache kontejneru ne?

**Comment by ujovlado** [comment]
Este to poadim. V tom apache containeri sa vlastne nemusi cakat, takze tam by receive-kill obsahoval len obyc. receive (https://github.com/keboola/syrup-queue/pull/103)

Potom by som (asi podla nejakej env RECEIVE_KILL_WAIT_FOR_PROGRAMS=1) spravil  nech to caka - to som spominal tu: https://github.com/keboola/syrup-queue/issues/102#issuecomment-500311678

A nakoniec teda posledny krok, asi tiez podl env RECEIVE_KILL_GARBAGE_COLLECT=1, urobil, nech to po sebe uprace.
