### ISSUE TITLE
Deprecated message

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-queue#2]
Apr 08 13:35:08 kbc-vpc-syrup-docker-worker-i-20fb12bd queue:  {
message: Not quoting the scalar "@logger" starting with "@" is deprecated since Symfony 2.8 and will throw a ParseException in 3.0.
context: {
type: 16384
file: /www/syrup-router/components/queue/releases/1460115229/vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php
line: 241
level: 28928
}
level: 200
channel: php
extra: {
}
cliCommand: /www/syrup-router/components/queue/current/vendor/keboola/syrup/app/console syrup:queue:receive-kill
component: queue
runId: null
pid: 11046
priority: INFO
}

**Comment by Halama** [comment]
Apr 08 13:35:08 kbc-vpc-syrup-docker-worker-i-20fb12bd queue:  {
message: Not quoting the scalar "@doctrine.dbal.limit_lock_connection" starting with "@" is deprecated since Symfony 2.8 and will throw a ParseException in 3.0.
level: 200
cliCommand: /www/syrup-router/components/queue/current/vendor/keboola/syrup/app/console syrup:queue:receive-kill
component: queue
runId: null
pid: 11046
priority: INFO
attachment: https://connection.keboola.com/admin/utils/logs?file=2016/04/08/2016-04-08-13-35-08-5707976c30aba-log
}
Apr 08 13:35:08 kbc-vpc-syrup-docker-worker-i-20fb12bd queue:  {
message: Not quoting the scalar "@syrup.elasticsearch.search" starting with "@" is deprecated since Symfony 2.8 and will throw a ParseException in 3.0.
level: 200
cliCommand: /www/syrup-router/components/queue/current/vendor/keboola/syrup/app/console syrup:queue:receive-kill
component: queue
runId: null
pid: 11046
priority: INFO
attachment: https://connection.keboola.com/admin/utils/logs?file=2016/04/08/2016-04-08-13-35-08-5707976c38ce7-log
}

**Comment by MiroCillik** [comment]
Jo, viem o tom, bude treba upravit services.yml v Syrupe podla tohto noveho standartu

**Comment by ujovlado** [comment]
already fixed by f9e1f99e1d2334918515225458c774331e068258
