### ISSUE TITLE
EsRejectedExecutionException

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup-queue#49]
retry?

https://connection.keboola.com/admin/utils/logs?file=2017/01/30/06/2017-01-30-06-16-39-588ecc37c05d0-exception
https://connection.keboola.com/admin/utils/logs?file=2017/01/30/06/2017-01-30-06-16-39-588ecc37de5d9-log

**Comment by Halama** [comment]
Souviselo s přetíženým Elasticem a plnou frontou požadavků. Nově je v metrikách Elasticu a máme na to alarm. Za běžného provozu by se stávat nemělo. Pokud ano je Elastic přetížený.
