### ISSUE TITLE
Debordelizace queue

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-queue#5]
## Na začátek

- Smazání syrup 3.1 a výše
- Do masteru syrup-queue dostat to co je na production branch (tag 6.0.2)
- Zprovoznit integraci - po push do masteru se to nasadí na testing a tam se to otestuje, můžou se spustit joby ze syrup devel projektu např. nebo udělat nějaké fake komponenty na testování
- Odstranit ze syrup-queue hlídání limitů a vše co souvisí s protocol v2
- Nenasazovat na produkci - budu to chtít vždy zkontrolovat, a dál bych se o to asi staral

## Co dál
Zatím to necháme tak že limity kontroluje syrup, protože tohle jak to bylo udělaný teď fungovalo úplně jinak než mělo. Možná by se to dalo řešit podobně jako na travisu https://github.com/travis-ci/travis-scheduler ale taky tam vidím nějaká úskalí.

**Comment by MiroCillik** [comment]
All done

**Comment by Halama** [comment]
super, mrknu na to az se k tomu dostanu

**Comment by Halama** [comment]
Navazující issue https://github.com/keboola/syrup-queue/issues/6

**Comment by Halama** [comment]
odpol mrknu na tohle a nasadim kdyztak, pak zavru a uvidime co dal.

**Comment by Halama** [comment]
nasadil jsem to, zatim ok
