### ISSUE TITLE
Add "exponencial sleep" on zero documents found 

### ISSUE THREAD

**Issue by ujovlado** [keboola/syrup-queue#55]
`MetricsProcessElasticStatsCommand`

**Comment by Halama** [comment]
klidne to zitra udelam...

**Comment by Halama** [comment]
@ujovlado jedu dnes ruzne drobnosti tak se vrhnu ted na tohle ok?

**Comment by ujovlado** [comment]
@Halama mam to uz rozrobene :)

**Comment by Halama** [comment]
ok, jsem prave nevedel, tak to nechavam

**Comment by ujovlado** [comment]
rano, ked sa to objavilo, zacal som to robit, no potom som odbehol k UI
