### ISSUE TITLE
Manage API na spravovanie instancii, ktore maju/nemaju robit receive message

### ISSUE THREAD

**Issue by ujovlado** [keboola/syrup-queue#58]
Potrebovali by sme manage api call, ktorym by bolo mozne "odregistrovat" instanciu z prijimania messages z queue.

- Instancia, ktora bude takto odregistrovana by nemala dalej robit queue receive.
- T.j. uz by na nej len dobehli joby, ktore bezia a cau
- queue receive command by sa predtym nez ide pollovat frontu pozrel, ci nie je na instancii, ktora je urcena na odobratie (ak ano, dal by sa do nejakeho "sleep mode" a neodoberal by ziadne messages)

Takze by mal vzniknut novy endpoint a par api callov a Queue Manage API.

**Comment by Halama** [comment]
Vyřeší se v rámci první fáze dockerizace https://github.com/keboola/syrup-router/issues/164
