### ISSUE TITLE
Switch Dynamo to On Demand Mode

### ISSUE THREAD

**Issue by Halama** [keboola/syrup-queue#81]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html

Mohlo by ušetřit $ a odstranit starosti s laděním propustnosti.
Ověřit jestli tam nejsou nějaká úskalí.

**Comment by ujovlado** [comment]
O tomto som cital, kludne si to prihodim do todo

**Comment by Halama** [comment]
super. Vzpomněl jsem si na to protože zas ladím https://keboola.slack.com/archives/C02CGK5CL/p1544001872045800

**Comment by MiroCillik** [comment]
Aha, ten On-Demand je este nieco ine/novsie ako ten auto-scaling, lebo tam bol prave problem, ze to chvilu trvalo kym sa to vyskalovalo, toto by malo byt okamzite. To potom mozem pouzit aj u OAuthu.

**Comment by ujovlado** [comment]
Presiel som si to cele, switchol by som to. Nemali by tam nastat ziadne problemy.

> Existing table switched to on-demand capacity mode: The previous peak is the maximum previous WCUs and RCUs provisioned for the table.

to je cajk, zobere maxima

> During the switching period, your table delivers throughput that is consistent with the previously provisioned write capacity unit and read capacity unit amounts.

pocas migraciu to doda vykon ako bol nastaveny v provisioned, ziadna degradacia

> On-demand capacity mode instantly accommodates up to double the previous peak traffic on a table.

toto presne chceme, ked to vyskoci, nech sa to prisposobi.

> However, throttling can occur if you exceed double your previous peak within 30 minutes.

toto sa nam nestava tak casto, ze by sme 2x prekrocili

**Comment by ujovlado** [comment]
Spravim to manualne z console, potom by som upravil CF template by v pripadne noveho regionu uz pozakladalo on-demand.

**Comment by Halama** [comment]
Tam kee to je přes CF tak je to potřeba upravit přes CF

**Comment by Halama** [comment]
mám pocit že v US to není přes CF tak tam ručně, jinde ne

**Comment by Halama** [comment]
a pak je otázka co s alarmy

**Comment by ujovlado** [comment]
Ok, tak kuknem este to.... Super by bolo, keby slo nastavit alarm na ten 2x peak napr.

**Comment by Halama** [comment]
https://github.com/keboola/syrup-router/blob/master/provisioning/dynamodb.json Ty na tu konzumovanou kapacitu ted nebudou dávat smysl, takže bych je dal pryč.

**Comment by Halama** [comment]
doporučujou nějaký alarmy na to? Můžeme dát asi na ten throttling když by trval nějak déle

**Comment by Halama** [comment]
normalně přes PR celé, nespěchá to

**Comment by ujovlado** [comment]
To som presne myslel, ze keby prisiel alarm na prekrocene RCU/WCU, tak by to zahucalo, ze mozeme ocakavat throttling -> niekto by to checkol nez throttling nastane :)

**Comment by ujovlado** [comment]
Ok

**Comment by Halama** [comment]
nerozumim jak by si ten alarm nastavil, jake hodnoty nad jakymi metrikami?

**Comment by Halama** [comment]
Možná tam nechat ty co jsou jenom v tech jednotlivých stackcích je zvednout třeba 2x aby to bylo jako pojistka že se to nějak neutrhne. Ten throtting si to pořeší samo tak na to asi alarm potřeba není.

**Comment by ujovlado** [comment]
ok, este som o tom premyslal.

1. ThrottledRequests by som tam nechal - je dobre vediet to, tam to realne dava 400ku
2. ConsumedReadCapacityUnits - dal by som tie 2 nasobky ako si vravel v tomto pripade 1400
3. ConsumedWriteCapacityUnits - tuna by som dal 100

s 1. nemusime robit nic a 2., 3. by som odladil podla toho ako sa to bude spravat.

**Comment by ujovlado** [comment]
^ pre US. Pre EU obdobne, podla hodnot tam.

**Comment by ujovlado** [comment]
Swith na on-demand a potom s5 na provisioned. Zatvaram. Vratime sa k tomu, ked budeme riesit presun casti stats z dynama do elasticu.
